apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: simple-topic
  labels:
    strimzi.io/cluster: simple-cluster
spec:
  partitions: 5
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824